.github/workflows/python-check.yml

Let's run most of the Makefile targets to make sure everything is ok before merging

CI: Create python-check.yml for github actions

---

README.md

When people discover the project, it's cool to give a quick overview of what are the dependencies to make this project being used.

README: Explicit the main requirements

---

requirements/base.in

The default rendering engine in hwgraph is cairo, so let's ensure the dependency is explicit to avoid any issue at rendering time.

requirements: Adding pycairo

---

.github/workflows/python-check.yml

If a pull request contains multiple commits, it is advisable to ensure that every single commit has been tested.
This modifies the python-check workflow to fetch all the commits in the pull request and iteratively run the 'make check' command on each of them. While we are at it, this slighly beautifies the output of the github workflow.

test: ensure every commit in a PR works

---

.github/workflows/python-check.yml

Commit d3105449f303 ("test: ensure every commit in a PR works") ensures that every commit in a pull request is tested. But the way it changes the github action makes it incompatible with being run on direct push.
Since direct push to main are forbidden, it makes sense to disable running tests in this case until a better solution is found.

Do not run test on direct push

---

hwbench/hwbench.py

Even if the setup requires a minimal python version, this doesn't prevent users from running a different python release at runtime.
This commit is about preventing hwbench to run on unsupported python releases.

hwbench: Ensure no one is running below the minimal python version

---

hwbench/tuning/power_profile.py

When no valid governor configuration is detected, the run() call will skip the tuning.
This skip is silent which could be confusing to understand.
This commit is adding an explicit log entry when the cpu profile tuning is skipped.

hwbench/tuning: Add specific log entry if tuning is skipped

---

hwbench/tuning/power_profile.py

The current code does not check if the scaling_governor is present before using it, leading to a crash.
To improve this part of the code, this commit is:
- considering the current_governor instead of the available ones to decide if the tuning should be done
- adding a check before actually reading the file and ignoring the function if no file is found
This commit fixes issue #25.

tuning: Avoid crash in PerformancePowerProfile

---

.github/ISSUE_TEMPLATE/✨-feature-request.md
.github/ISSUE_TEMPLATE/🆘-bug-report.md

This should allow easier bug reports and feature requests for users, with better troubleshooting for us

Add issue templates

---

hwbench/bench/test_benchmarks.py
hwbench/config/test_parse.py
hwbench/engines/stressng.py
hwbench/engines/stressng_cpu.py
hwbench/engines/stressng_memrate.py
hwbench/engines/stressng_qsort.py
hwbench/engines/stressng_stream.py
hwbench/engines/stressng_vnni.py
hwbench/engines/test_parse.py

As per issue #48 , stressng.py is 630 lines and is difficult to read.
This PR is about splitting this file to get 1 file per engine module.

Split Stress-ng code in multiple files

---

hwbench/environment/vendors/hpe/ilorest.py

If ilorest is not installed on a HPE server, a crash occurs.
This commit is about adding an explicit message to let the user know that ilorest is a mandatory tool for HPE-based systems.
A typical crash calltrace:
Traceback (most recent call last):
File "/root/hwbench/.venv/bin/hwbench", line 8, in <module>
sys.exit(main())
File "/root/hwbench/hwbench/hwbench.py", line 41, in main
hw = env_hw.Hardware(out_dir, args.monitoring_config)
File "/root/hwbench/hwbench/environment/hardware.py", line 43, in __init__
self.vendor = first_matching_vendor(out_dir, self.dmi, monitoring_config)
File "/root/hwbench/hwbench/environment/vendors/detect.py", line 26, in first_matching_vendor
v.prepare()
File "/root/hwbench/hwbench/environment/vendors/hpe/hpe.py", line 211, in prepare
self.ilo = ILOREST()
File …

HPE/ilorest: Do not crash if ilorest is missing

---

graph/trace.py

When hwgraph find an unsupported engine, it prints a message. This message is using the engine module name as the engine name making a confusing output.
This commit use the engine name instead of the engine module.

hwgraph: Fixing error message

---

hwbench/bench/benchmark.py
hwbench/utils/helpers.py
hwbench/utils/test_helpers.py

Related to [FEATURE] Improve CPU pinning reporting #49
Previously, when getting information on which CPU the benchmark was running, the string was not intelligently created, leading to really long outputs on CPUs with a lot of cores. Now, we try to be a little smarter:
- [0, 1, 2, 3, 4, 5] becomes "0-5"
- [0, 4, 2, 3, 7, 8, 9] becomes "0, 2-4, 7-9"
It should improve output readability and general UX.

feat: nicely display CPU affinity when running benchmarks

---

hwbench/bench/benchmark.py

Prior commit da6ecdcaa853dfe5b86d3c368ffbcd0a489864fb, the pinned output look like a list like in :
[randread_cmdline_0] fio/cmdline/cmdline(M):   4 stressor pinned on CPU [0, 1, 2, 3, 4, 5] for 9s
After this commit output looks like:
[randread_cmdline_0] fio/cmdline/cmdline(M):   4 stressor pinned on CPU 0-5 for 9s
This commit is about adding [] around the string to indicate its a list like in :
[randread_cmdline_0] fio/cmdline/cmdline(M):   4 stressor pinned on CPU [0-5] for 9s
This will be particulary helpful when the pinned list is composed of several intervals.

benchmark: Fix pinned CPU list display

---

hwbench/environment/cpu_info.py

Introduce a fallback so that CPU name detection still works.

environment: some CPU vendors might not expose a model name

---

hwbench/environment/vendors/detect.py
hwbench/environment/vendors/generic.py

We might want to use a generic redfish and PDU interface for some server vendors, or when running from a local machine.
MockVendor stays and should be used exclusively for tests. GenericVendor is when you want to test hwbench locally or on a server of new (yet unsupported) vendor.
Fixes #47

vendors: add a generic vendor

---

.github/workflows/python-check.yml

The default github action image moved from ubuntu 22.04 to 24.04, and its list of installed packages is not the same. Make sure we have libcairo-dev for pycairo, a dependency of matplotlib used by hwgraph.

github actions: fix installation after move to ubuntu 24.04

---

Makefile
csv/convert.py
graph/graph.py
graph/individual.py
graph/scaling.py
graph/trace.py
hwbench/config/config.py
hwbench/environment/turbostat.py
hwbench/environment/vendors/hpe/hpe.py
hwbench/utils/helpers.py

Pin ruff and bump it later. This fixes the formatting issues introduced in ruff 0.9.0, but now we always need to manually bump it.

Pin ruff tool

---

hwbench/utils/archive.py

This was removed in #70 mistakenly

utils: restore the error handling when extracting a file from a tar

---

hwbench/bench/benchmark.py

It does not work on python 3.9, and needs python 3.10. And it cannot be resolved with an import future.
https://docs.python.org/3/library/stdtypes.html#types-union

benchmark: roll back isinstance comparison with UnionType

---

hwbench/environment/vendors/vendor.py

It's now done directly in the BMC class appropriately. We did not find this before because we use the other vendor subclasses which override prepare.

vendor: remove duplicate find_monitoring_sections in default prepare

---

hwbench/environment/vendors/generic.py

Since we moved to the generic vendor, we no longer use the mockedvendor
by default (it's now only for tests). So when running hwbench on a
desktop/laptop for local testing, it requires setting the monitoring
file, which wasn't the case before.
This change makes the monitoring file optional in this case, with a
fallback when it is not provided to the MockedBMC.

hwbench: generic vendor: make monitoring file optional

---

README.md

As per issue #77, let's clarify the optional and
external dependency to SCELNX_64.

README: Explicit SCELNX_64 optional dependency

---

hwbench/environment/block_devices.py

It seems udev_attributes from block devices were all containing "b'value'" which indicates a bad string conversion from bytes. This is now fixed and should resolve #87

block_devices: fix bytes conversion in export

---

hwbench/bench/benchmarks.py
hwbench/bench/engine.py
hwbench/bench/test_benchmarks.py
hwbench/bench/test_benchmarks_common.py
hwbench/config/config.py
hwbench/config/config_syntax.py
hwbench/engines/stressng_cpu.py
hwbench/engines/test_parse_stressng.py
hwbench/environment/hardware.py
hwbench/hwbench.py
hwbench/utils/helpers.py

This should make the entry into the hwbench world easier. Now, instead of crashing once and for all if something is missing, it will collect everything missing, and then stop. This system can be easily expanded to add other kind of requirements.
For instance, it returns this when I'm missing those binaries:
```
CRITICAL:root:Requirements are not met: Binary smartctl is not available on the system
CRITICAL:root:Requirements are not met: Binary sdparm is not available on the system
CRITICAL:root:Requirements are not met: Binary stress-ng is not available on the system
CRITICAL:root:Requirements are not met: Binary fio is not available on the system
```

ux: crash early if a binary is not available, and display all the missing ones

---

hwbench/environment/memory.py
hwbench/environment/software.py

This is useful for our performance score calculator and is generally a good metric to dump I think

environment: include memory stats in the results
